version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip install -U black flake8 --user
      - run: black --check .
      - run: flake8 .
  build:
    working_directory: ~/working
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: sudo apt install -y cmake python-pybind11
      - run: git clone https://github.com/CGAL/cgal.git && cd cgal/ && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && sudo make install
      - run: pip install . --user
      - run: pip install -U pytest pytest-cov --user
      - run:
          command: pytest --cov oceanmesh
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
